### ISSUE TITLE
Takedown Request

### ISSUE THREAD

**Issue by Nanomotion** [Torotv/Torotv.github.io#2]
Hi!
I noticed that you have used my repository. It's great to see someone learn how to program and use code in a public environment. However, copying someone else's work is **not** programming, and it is a very disrespectful thing to do. I ask that you please remove this repository, or I will ask GitHub to perform a [DMCA takedown request](https://help.github.com/articles/dmca-takedown-policy/). I have already been working with them as to find a solution.
![image](https://user-images.githubusercontent.com/19719195/31099292-7d790b66-a793-11e7-88eb-4d5790dd7a49.png)
If you would like to talk with me about this in private, send me an email at [admin@nanomotion.xyz](mailto:admin@nanomotion.xyz).

Please respond in the next 24 hours if you can.
Thanks,
Nanomotion

**Comment by Torotv** [comment]
Hello Nano,

I Have Changed Many things Now Is Tottllty Differnt.
BTW: That's A Email From Vuton KT @vutondesign.
Thanks. I Have Delated Some OF Yours and Vuton's Copy!
